services:

  mysql-db:
    container_name: mysql-practice
    image: mysql:latest
    restart: always
    env_file:
      - ".prod.env"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    depends_on:
      - mysql-db
    container_name: phpmyadmin-practice
    image: phpmyadmin/phpmyadmin:latest
    env_file:
      - ".prod.env"
    restart: always
    ports:
      - "8080:80"
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  mysql-data: